<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetDiagTool.Core\NetDiagTool.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Networking\" />
    <Folder Include="Detection\" />
    <Folder Include="Parsing\" />
  </ItemGroup>

</Project>
